---
# tasks file for apache
- name: install Apache
  yum:
    name: "{{ pkg_name }}"
    state: present
- name: copy index file
  copy:
    src: file/index.html
    dest: "{{/var/www.html}}"
    remote_src: no
    notify: restart apache